django/belt_reviewer/apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    url(r'^$', views.index, name='home'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^show/(?P<book_id>\d+)$', views.show, name='show'),
    url(r'^update/(?P<book_id>\d+)$', views.update, name='update'),
    
    
    
    ]

django/belt_reviewer/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^(?P<user_id>\d+)$', views.show, name='show'),
    url(r'^register$', views.register, name='register'),
    url(r'^login', views.login, name='login'),
    ]

django/belt_reviewer/confbeltrev/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.users import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^$', views.index, name="register")
    

]

django/belt_reviewer/apps/books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..users.models import User

class Author(models.Model):
    name= models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=255)
    author=models.OneToOneField(Author)
    
    def __str__(self):
        return self.title
       
class Review(models.Model):
    content= models.TextField()
    rating=models.IntegerField()
    book=models.ForeignKey(Book, related_name='reviews')
    user=models.ForeignKey(User, related_name='reviews')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_at"]
    
    def __str__(self):
        return self.content[:50] + '...'



    

django/belt_reviewer/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
regex_obj = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

class RegistrationManager(models.Manager):
    def regvalidation(self, regdata):
        errors = []
        if len(regdata['first_name']) < 2 or len(regdata['last_name']) < 2:
            errors.append('First and last name must be at least 2 characters in length.')
        if not regex_obj.match(regdata['email']):
            errors.append('Please enter a valid email address')
        if len(regdata['password1']) < 8 or regdata['password1'] != regdata['password2']:
            errors.append('Password must be at least 8 characters long and match')
        if User.objects.filter(email=regdata['email']).exists():
            errors.append("This email address is already registered with a user.")
        return errors
        
        
class User(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.EmailField()
    password = models.CharField(max_length=55)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    objects=RegistrationManager()

django/belt_reviewer/apps/books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from .models import *

def index(request):
    reviews = Review.objects.all()
    books = Book.objects.values('title', 'id')
    return render(request, 'books/index.html', {'reviews':reviews[:5], 'books':books})

def new(request):
    return render(request, 'books/new.html')
    
def create(request):
    a = Author(name=request.POST['new_author'])
    a.save()
    b = Book(title=request.POST['title'], author=a)
    b.save()
    r = Review(content=request.POST['content'], rating=request.POST['rating'], book=b)
    r.save()
    return redirect('show/' + str(b.id))
    
def update(request, book_id):
    book =Book.objects.get(id=book_id)
    new_review = Review(content=request.POST['review'], rating=request.POST['rating'], book=book)
    new_review.save()
    return redirect('/books/show/' + book_id)
    
def show(request, book_id):
    book = Book.objects.get(id=book_id)
    reviews = book.reviews.all()
    context={'book': book, 'reviews': reviews}
    return render(request, 'books/show.html', context)
    

django/belt_reviewer/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User
import bcrypt


def index(request):
    return render(request, 'users/register.html')

def show(request, user_id):
    profile = User.objects.get(id=user_id)
    reviews = profile.reviews.all()
    return render(request, 'users/show.html', {'user':profile, 'reviews': reviews})
    
def register(request):
    errors=User.objects.regvalidation(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error)
            return redirect('/')
    else:
        password = request.POST['password1']
        safepw= bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        auth_user=User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'],email=request.POST['email'],password=safepw)
        print (auth_user)
        request.session['auth']=True
        messages.success(request, 'You are now registered! Welcome, ' + request.POST['first_name'] + '!')
        return redirect('/books')


def login(request):
    return HttpResponse('login')

django/belt_reviewer/apps/books/templates/books/base.html
<!--base for beltreviewer-->

<!DOCTYPE html>
<html lang='en'>

<head>
    <title>{%block title%}{%endblock title%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load static%}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="{% static 'books/css/styles.css' %}" type="text/css" />

</head>

<body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class="container">
            <ul class='nav navbar-nav navbar-right'>
                <li><a href="{% url 'books:home'%}">Home</a></li>
                <li><a href="#"></a>Logout</li>

            </ul>
        </div>
    </nav>
    <div class="container">

        {%block content%} {%endblock content%}
    </div>
</body>

</html>

django/belt_reviewer/apps/books/templates/books/index.html
{%extends 'books/base.html' %} {%block title%}Books Home{%endblock title%} {%block content%}

{%if messages %} {% for message in messages %}
    <p class='alert alert-{{message.tags}}'>{{message}}</p>
    {%endfor%} {%endif%}

<div class='listing'>
    <h4>Recent Book Reviews:</h4>
    {% for review in reviews %}
    <h5><a href='show/{{review.book_id}}'>{{review.book.title.title}}</a></h5>
    <div id='stars'>
        {% if review.rating == 5%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span> {%elif review.rating == 4%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734; {%elif review.rating == 3%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734;&#9734; {%elif review.rating == 2%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734;&#9734;&#9734; {%elif review.rating == 1%}
        <span id='yellow'>&#9733;</span>&#9734;&#9734;&#9734;&#9734; {%endif%}
    </div>
    <p class="review"><a href="{% url 'users:show' review.user_id%}">{{review.user.first_name}}</a>: {{review.content}}</p>
    <p class="review">Posted on: {{review.created_at|date:'M d, Y H:i'}}</p>
    <hr> {%endfor%}
</div>
<div class='listing'>
    <p><a id="add" href="{% url 'books:new' %}">Add a new book</a></p>
    <h4>Other Books with Reviews:</h4>
    <div class='booklist'>
        {%for book in books%}
        <p><a href='show/{{book.id}}'>{{book.title}}</a></p>
        {%endfor%}
    </div>
</div>


{%endblock content%}

django/belt_reviewer/apps/books/templates/books/new.html
{%extends 'books/base.html' %}

{%block title%}Add Book and Review{%endblock title%}

{%block content%}
<h1>Add New Book Title and a Review:</h1>
<form action='{% url "books:create"%}' method='POST'>
    {% csrf_token %}
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="title">Book Title:</label>
    <div class="col-sm-6">
        <input class="form-control" id="title"  type="text" name="title" required/>    
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="new_author">Author:</label>
    <div class="col-sm-6">
        <input class="form-control" id="new_author"  type="text" name="new_author" required/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="content">Review: </label>
    <div class="col-sm-10">
        <input class="form-control" id='content' type="textarea" name="content" required/>    
        </div>
    </div>
    <div class="form-group row">
    <textarea name='review' cols="50" rows='5'></textarea>
    <p>Rating: <select  id='rating' name="rating"/>  
            <option name='rating' value='1'>1</option>
            <option name='rating' value='2'>2</option>
            <option name='rating' value='3'>3</option>
            <option name='rating' value='4'>4</option>
            <option name='rating' value='5'>5</option>
        </select>
        </div>
    </div>
    <div class="form-group row">
        <p class='form control col-sm-10' </p>
        <input class="float-right col-sm-2" type="submit" value="Add Book and Review"/>
</form>

{%endblock content%}

django/belt_reviewer/apps/books/templates/books/show.html
{%extends 'books/base.html' %} {%block title%} {%endblock title%} {%block content%}

<div class="listing">
    <h2>{{book.title.title}}</h2>
    <h4>Author: {{book.author}}</h4>
    {%for review in book.reviews.all%}

    <div id='stars'>
        {% if review.rating == 5%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span> {%elif review.rating == 4%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734; {%elif review.rating == 3%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734;&#9734; {%elif review.rating == 2%}
        <span id='yellow'>&#9733;</span>
        <span id='yellow'>&#9733;</span>&#9734;&#9734;&#9734; {%elif review.rating == 1%}
        <span id='yellow'>&#9733;</span>&#9734;&#9734;&#9734;&#9734; {%endif%}
    </div>
    <p id='review'>-{{review.content}}</p>
    {%endfor%}
</div>

<div class='addrev'>
    <h3>Add a Review:</h3>
    <form action="{%url 'books:update' book.id %}" method='POST'>
        {%csrf_token%}
        <p>Star Rating:
            <select id='rating' name="rating" />
            <option name='rating' value='1'>1</option>
            <option name='rating' value='2'>2</option>
            <option name='rating' value='3'>3</option>
            <option name='rating' value='4'>4</option>
            <option name='rating' value='5'>5</option>
            </select>
        </p>
        <textarea name='review' cols="50" rows='5'></textarea>
        <input type='submit' value='Submit Review'>
    </form>
</div>


{%endblock content%}

django/belt_reviewer/apps/users/templates/users/register.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <title>{%block title%}{%endblock title%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load static%}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="{% static 'books/css/styles.css' %}" type="text/css" />

</head>
<div class='container'>
    <h1>Login and Registration</h1> {%if messages %} {% for message in messages %}
    <p class='alert alert-{{message.tags}}'>{{message}}</p>
    {%endfor%} {%endif%}

    <div class='row'>
        <div id='col'>
            <form action='{% url "users:register"%}' method='POST'>

                <h3>Register:</h3>{% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="first_name">First Name:</label>
                    <div class="col-sm-4">
                        <input required class="form-control" id="first_name" type="text" name="first_name" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="last_name">Last Name:</label>
                    <div class="col-sm-4">
                        <input required class="form-control" id="last_name" type="text" name="last_name" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="email">Email: </label>
                    <div class="col-sm-4">
                        <input required class="form-control" id='email' type="textarea" name="email" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="password1">Password: </label>
                    <div class="col-sm-4">
                        <input required class="form-control" id='password1' type="password" name="password1" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="password2">Confirm Password: </label>
                    <div class="col-sm-4">
                        <input required class="form-control" id='password2' type="password" name="password2" />
                    </div>
                </div>
                <div class="form-group row">
                    <p class='form control col-sm-10' </p>
                        <input class="float-right col-sm-2" type="submit" value="Register" />
                </div>

            </form>
        </div>
        <div id='col'>
            <form action='{% url "users:login"%}' method='POST'>

                <h3>Log In:</h3> {% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="email">Email: </label>
                    <div class="col-sm-4">
                        <input  required class="form-control" id='email' type="textarea" name="email" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="password">Password: </label>
                    <div class="col-sm-4">
                        <input  required class="form-control" id='password' type="textarea" name="password" />
                    </div>
                </div>
                <div class="form-group row">
                    <pc class='col-sm-8'>
                        </p>
                        <input class='float-right col-sm-2' type="submit" value="Log In" />
                </div>

            </form>
        </div>
    </div>
</div>

django/belt_reviewer/apps/users/templates/users/show.html
{%extends 'books/base.html' %} {%block title%}User Profile{%endblock title%} {%block content%}

<div class="listing">
    <h2>{{user.first_name.title}} {{user.last_name.title}}</h2>
    <h4>Email: {{user.email}}</h4>
    <p>Total Review:</p>
</div>
<div class=''>
    <p>Posted Reviews on the following books:</p>
    {% for review in reviews%}
            <p><a href={%url 'books:show' review.book.id %}>{{review.book.title}}</a></p>
    {%endfor%}

</div>


{%endblock content%}