django/user_dashboard/apps/userdash/urls.py
"""urls for userdash"""
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register', views.register, name='register'),
    
    ]

django/user_dashboard/confuserdash/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.userdash.urls', namespace='userdash'))
]

django/user_dashboard/apps/userdash/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Member(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.EmailField()
    password = models.CharField(max_length=55)


class User(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.EmailField()
    password = models.CharField(max_length=55)
    

django/user_dashboard/apps/userdash/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse

def index(request):
    return render(request, 'userdash/index.html')
    
def login(request):
    return render(request, 'userdash/login.html')
    
def register(request):
    return render(request, 'userdash/register.html')
    

django/user_dashboard/apps/userdash/templates/userdash/base.html
      <!doctype html>
<html lang="en">
  <head>
    <title>{%block title%}
{%endblock title%}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
 
    </head>
    <body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
        

  <a class="navbar-brand" href="#">Test App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
 
        <a class="nav-link float-right" href="{% url 'userdash:login'%}">Log In</a>
   
  </div>
</nav>
<div class="container">
         {%block content%}
         
         
         
            
        
        {%endblock content%}        
        </div>
    </body>
</html>

django/user_dashboard/apps/userdash/templates/userdash/edit.html
{% extends 'userdash/base.html' %}

{%block title%}
{%endblock title%}


{%block content%}
{%endblock content%}

django/user_dashboard/apps/userdash/templates/userdash/index.html
{% extends 'userdash/base.html' %}

{%block title%}Home Page
{%endblock title%}


{%block content%}
<div class="jumbotron">
  <h1 class="display-3">Welcome to the Test!</h1>
  <p class="lead">This is an application utalizing a MVC framework -- allowing users to leave messages and add comments to other users.</p>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'userdash:login' %}" role="button">Start</a>
  </p>
</div>
{%endblock content%}

django/user_dashboard/apps/userdash/templates/userdash/login.html
{% extends 'userdash/base.html' %}

{%block title%}Log In
{%endblock title%}


{%block content%}
<h1>Log In:</h1>
    <form action='{% url "userdash:login"%}' method='POST'>
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" for="email">Email: </label>
            <div class="col-sm-6">
                <input class="form-control" id='email' type="textarea" name="email"/>    
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" for="password">Password: </label>
            <div class="col-sm-6">
                <input class="form-control" id='password' type="textarea" name="password"/>    
            </div>
        </div>
        <div class="form-group row">
            <pc class='col-sm-8'></p>
        <input class='float-right col-sm-2' type="submit" value="Log In"/>
    </form>
    <a href="{% url 'userdash:register'%}">Don't have an account? Register</a>
    
{%endblock content%}

django/user_dashboard/apps/userdash/templates/userdash/new.html
{% extends 'userdash/base.html' %}

{%block title%}
{%endblock title%}


{%block content%}
{%endblock content%}

django/user_dashboard/apps/userdash/templates/userdash/register.html
{% extends 'userdash/base.html' %}

{%block title%}Register
{%endblock title%}


{%block content%}
<h1>Register:</h1>
<form action='{% url "userdash:register"%}' method='POST'>
    {% csrf_token %}
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="first_name">First Name:</label>
    <div class="col-sm-6">
        <input class="form-control" id="first_name"  type="text" name="first_name"/>    
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="last_name">Last Name:</label>
    <div class="col-sm-6">
        <input class="form-control" id="last_name"  type="text" name="last_name"/>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="email">Email: </label>
    <div class="col-sm-6">
        <input class="form-control" id='email' type="textarea" name="email"/>    
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="password1">Password: </label>
    <div class="col-sm-6">
        <input class="form-control" id='password1' type="textarea" name="password1"/>    
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" for="password2">Confirm Password: </label>
    <div class="col-sm-6">
        <input class="form-control" id='password2' type="textarea" name="password2"/>
        </div>
    </div>
    <div class="form-group row">
        <p class='form control col-sm-10' </p>
        <input class="float-right col-sm-2" type="submit" value="Register"/>
</form>
{%endblock content%}

django/user_dashboard/apps/userdash/templates/userdash/show.html
{% extends 'userdash/base.html' %}

{%block title%}
{%endblock title%}


{%block content%}
{%endblock content%}s