django/dojo_ninjas/apps/book_authors/urls.py
from django.conf.urls import url
from . import views
urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    ]

django/dojo_ninjas/dn_conf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.book_authors.urls', namespace='book_authors') )
]

django/dojo_ninjas/apps/book_authors/models.py
'''models for book_authors app'''

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class BookManager(models.Manager):
    def  validate_fields(self, data):
        errors = []
        if len(data['name']) < 5:
            errors.append('name must be 5 characters')
            print(errors)
        return errors

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email= models.EmailField()
    notes= models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.first_name

class Book(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    authors = models.ManyToManyField(Author, related_name='books')
    objects = BookManager()
    
    def __str__(self):
        return self.name
        

    

django/dojo_ninjas/apps/dn_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Dojo(models.Model):
    name = models.CharField(max_length=25)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=2)
    desc = models.TextField()
    
    
class Ninja(models.Model):
    dojo = models.ForeignKey(Dojo, related_name='ninjas')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    
    

django/dojo_ninjas/apps/book_authors/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Book, Author
from django.contrib import messages

def index(request):
    books = Book.objects.all()
    context = {'books' : books}
    return render(request, 'book_authors/index.html', context)
    
def new(request):
    if request.method != 'POST':
        return render(request, 'book_authors/new.html')
    else:
        errors = Book.objects.validate_fields(request.POST)
        
        if len(errors)>0:
            for error in errors:
                messages.error(request, error)
            # context ={'messages':messages.error(request,  errors['text'])}
            return render(request, "book_authors/new.html")
        else:
            book=Book(name=request.POST['name'], desc=request.POST['desc'])
            book.save()
            author=Author(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email = request.POST['email'], notes=request.POST['notes'])
            author.save()
            book.authors.add(author)
            return redirect('/')
    

django/dojo_ninjas/apps/dn_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

django/dojo_ninjas/apps/book_authors/templates/book_authors/index.html
<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body>
 
        {{books}}
        {%for book in books%}
            <p>{{book.name}}</p>
            <p>    by: {% for author in book.authors.all%} {{author.first_name}} {{author.last_name}}, {%endfor%}</p>
            <hr>
        {% endfor%}
        <a href="{% url 'book_authors:new'%}">add new book</a>
    </body>
</html>

django/dojo_ninjas/apps/book_authors/templates/book_authors/new.html
<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body>
        
        {%if messages%}
        {%for message in messages%}
        {{message}}
       
        {%endfor%} {%endif%}
        <form action={% url 'book_authors:new'%} method='POST'>
            {% csrf_token%}
            <label for="name">Title:</label>
            <input id='name' type="text" name="name"/>            
            <label for="desc">Description:</label>
            <input id='desc' type="text" name="desc"/>
            <p>Author Information:</p>
            <label for="first_name">First Name:</label>
            <input id='first_name' type="text" name="first_name"/>            
            <label for="last_name">Last Name:</label>
            <input id='last_name' type="text" name="last_name"/>            
            <label for="email">Email:</label>
            <input id='email' type="text" name="email"/>            
            <label for="notes">Notes:</label>
            <input id='notes' type="text" name="notes"/>
            <input type="submit" value="Add Book"/>
        </form>
    </body>
</html>